"use client"

import { Link } from "react-router-dom"
import {
  Globe,
  Mail,
  FileText,
  Bot,
  Search,
  Bell,
  User,
  LogOut,
  ChevronRight,
  Shield,
  FileCheck,
  Zap,
  Sparkles,
} from "lucide-react"

import { Button } from "../components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../components/ui/card"
import { Avatar, AvatarFallback, AvatarImage } from "../components/ui/avatar"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "../components/ui/dropdown-menu"
import { Badge } from "../components/ui/badge"
import { useEffect, useState } from "react"
import axios from "axios"
import { BACKEND_URL } from "@/config"
import { useNavigate } from "react-router-dom"

const Dashboard = () => {
  const [user, setUser] = useState<{ name: string; username: string } | null>(null)

  const features = [
    {
      id: "verify-websites",
      title: "Project Authenticator",
      description: "Detect plagiarized content across projects and identify potential copyright infringements.",
      icon: Globe,
      color: "bg-gradient-to-br from-[#5068c9] to-[#4056b8]",
      stats: "98% accuracy",
      path: "/verify-websites",
      available: true,
    },
    {
      id: "phishing-emails",
      title: "Phishing Emails",
      description: "Identify suspicious emails and protect against phishing attempts with advanced detection.",
      icon: Mail,
      color: "bg-gradient-to-br from-red-500/30 to-red-600/30",
      stats: "2,456 threats blocked",
      available: false,
    },
    {
      id: "verify-documents",
      title: "Verify Documents",
      description: "Check documents for plagiarism against a vast database of academic and published works.",
      icon: FileText,
      color: "bg-gradient-to-br from-green-500/30 to-green-600/30",
      stats: "10M+ documents indexed",
      available: false,
    },
    {
      id: "ai-detection",
      title: "AI Content Detection",
      description: "Identify content generated by AI tools like ChatGPT, Bard, and other language models.",
      icon: Bot,
      color: "bg-gradient-to-br from-purple-500/30 to-purple-600/30",
      stats: "95% detection rate",
      available: false,
    },
  ]

  useEffect(() => {
    async function fetchUser() {
      try {
        const response = await axios.get(`${BACKEND_URL}/api/v1/verify/getUserData`, {
          headers: {
            Authorization: `${localStorage.getItem("token")}`,
          },
        })
        if (response.status === 200) {
          setUser(response.data)
        }
      } catch (err) {
        console.error("Error fetching user", err)
      }
    }

    fetchUser()
  }, [])

  const currentTime = new Date().getHours()
  const getGreeting = () => {
    if (currentTime < 12) return "Good morning"
    if (currentTime < 18) return "Good afternoon"
    return "Good evening"
  }

  const navigate = useNavigate()
  const handleLogout = () => {
    localStorage.removeItem("token")
    setUser(null)
    navigate("/sign-in")
  }

  return (
    <div className="flex min-h-screen flex-col" style={{ background: "#090e27" }}>
      <header
        className="sticky top-0 z-10 border-b border-gray-800/50 backdrop-blur-xl"
        style={{ backgroundColor: "#0d0e16" }}
      >
        <div className="flex h-16 items-center justify-between px-6 md:px-10">
          <div className="flex items-center gap-4">
            <Link to="/" className="flex items-center gap-2">
              <Shield className="h-6 w-6" style={{ color: "#5068c9" }} />
              <span className="text-xl font-bold text-white">SecureSight</span>
            </Link>
            <Badge
              variant="outline"
              className="border-[#5068c9]/50 text-white"
              style={{ backgroundColor: "#5068c9", borderColor: "#5068c9" }}
            >
              <Sparkles className="mr-1 h-3 w-3" />
              Premium
            </Badge>
          </div>

          <div className="flex items-center gap-4">
            <Button
              variant="outline"
              size="icon"
              className="border-gray-700/50 bg-gray-800/30 text-gray-300 hover:bg-gray-700/50 hover:text-white"
            >
              <Search className="h-4 w-4" />
              <span className="sr-only">Search</span>
            </Button>

            <Button
              variant="outline"
              size="icon"
              className="border-gray-700/50 bg-gray-800/30 text-gray-300 hover:bg-gray-700/50 hover:text-white"
            >
              <Bell className="h-4 w-4" />
              <span className="sr-only">Notifications</span>
            </Button>

            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="relative h-8 w-8 rounded-full">
                  <Avatar className="h-8 w-8 ring-2 ring-[#5068c9]">
                    <AvatarImage src="/placeholder.svg?height=32&width=32" alt="User" />
                    <AvatarFallback
                      className="text-white font-semibold"
                      style={{ background: "linear-gradient(135deg, #5068c9 0%, #4056b8 100%)" }}
                    >
                      {user?.name
                        ?.split(" ")
                        .map((n) => n[0])
                        .join("") || "US"}
                    </AvatarFallback>
                  </Avatar>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent
                className="w-56 backdrop-blur-xl border-gray-800/50 text-white"
                style={{ backgroundColor: "#13151f" }}
                align="end"
                forceMount
              >
                <DropdownMenuLabel className="font-normal">
                  <div className="flex flex-col space-y-1">
                    <p className="text-sm font-medium leading-none">{user?.name || "Loading..."}</p>
                    <p className="text-xs leading-none text-gray-400">{user?.username || ""}</p>
                  </div>
                </DropdownMenuLabel>
                {/* <DropdownMenuSeparator className="bg-gray-800/50" /> */}
                {/* <DropdownMenuItem className="text-gray-300 hover:bg-gray-800/50 hover:text-white">
                  <User className="mr-2 h-4 w-4" />
                  <span>Profile</span>
                </DropdownMenuItem>
                <DropdownMenuItem className="text-gray-300 hover:bg-gray-800/50 hover:text-white">
                  <Shield className="mr-2 h-4 w-4" />
                  <span>Security</span>
                </DropdownMenuItem> */}
                <DropdownMenuSeparator className="bg-gray-800/50" />
                <DropdownMenuItem className="text-gray-300 hover:bg-gray-800/50 hover:text-white">
                  <Button onClick={handleLogout} className="w-full text-left flex items-center gap-2">
                    <LogOut className="mr-2 h-4 w-4" />
                    <span>Log out</span>
                  </Button>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>

      <main className="flex-1 px-6 py-8 md:px-10">
        {/* Simplified Welcome Section */}
        {user && (
          <div className="mb-12">
            <div
              className="relative overflow-hidden rounded-2xl p-8 border"
              style={{
                background: "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 50%, #1e40af 100%)",
                borderColor: "#5068c9/30",
              }}
            >
              <div className="flex items-center justify-between">
                <div>
                  <h1 className="text-3xl font-bold text-white mb-2">
                    {getGreeting()}, <span className="text-blue-200">{user.name}</span>! 👋
                  </h1>
                  <p className="text-blue-100 text-lg">
                    Ready to secure your digital world? Your verification tools are at your fingertips.
                  </p>
                </div>
                <div className="opacity-30">
                  <Shield className="h-16 w-16 text-white" />
                </div>
              </div>
            </div>
          </div>
        )}

        <div className="mb-12">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 rounded-lg" style={{ background: "linear-gradient(135deg, #5068c9 0%, #4056b8 100%)" }}>
              <Zap className="h-5 w-5 text-white" />
            </div>
            <h2 className="text-2xl font-bold text-white">Verification Tools</h2>
            <p className="text-gray-400">Choose a tool to start your security analysis</p>
          </div>

          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
            {/* Project Authenticator - Available */}
            <Card
              key="verify-websites"
              className="group backdrop-blur-sm border text-white transition-all duration-300 hover:shadow-lg transform hover:scale-[1.02] relative"
              style={{
                backgroundColor: "#13151f/90",
                borderColor: "#5068c9/50",
                boxShadow: "0 0 15px rgba(80, 104, 201, 0.2)",
              }}
            >
              <div className="absolute -top-2 -right-2 z-10">
                <Badge
                  className="animate-pulse text-xs font-bold px-2 py-1 text-white border-0"
                  style={{ backgroundColor: "#22c55e" }}
                >
                  LIVE
                </Badge>
              </div>

              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <div
                    className="flex h-12 w-12 items-center justify-center rounded-xl shadow-lg group-hover:scale-110 transition-transform duration-300"
                    style={{ background: "linear-gradient(135deg, #5068c9 0%, #4056b8 100%)" }}
                  >
                    <Globe className="h-6 w-6 text-white" />
                  </div>
                  <Badge variant="outline" className="border-gray-700/50 bg-gray-800/30 text-gray-300 text-xs">
                    98% accuracy
                  </Badge>
                </div>
                <CardTitle className="mt-4 text-lg text-white group-hover:text-[#5068c9] transition-colors duration-300">
                  Project Authenticator
                </CardTitle>
                <CardDescription className="text-gray-300 leading-relaxed text-sm">
                  Detect plagiarized content across projects and identify potential copyright infringements.
                </CardDescription>
              </CardHeader>
              <CardFooter>
                <Button
                  asChild
                  className="w-full text-white hover:text-white border transition-all duration-300"
                  style={{
                    backgroundColor: "#5068c9",
                    borderColor: "#5068c9",
                  }}
                >
                  <Link to="/verify-websites" className="flex items-center justify-between">
                    <span>Launch Tool</span>
                    <ChevronRight className="h-4 w-4 group-hover:translate-x-1 transition-transform duration-300" />
                  </Link>
                </Button>
              </CardFooter>
            </Card>

            {/* Phishing Emails - Coming Soon */}
            <Card
              key="phishing-emails"
              className="group backdrop-blur-sm border text-white transition-all duration-300 hover:shadow-lg transform hover:scale-[1.02]"
              style={{
                backgroundColor: "#13151f/90",
                borderColor: "#ef4444/30",
              }}
            >
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-red-500 to-red-600 shadow-lg group-hover:scale-110 transition-transform duration-300">
                    <Mail className="h-6 w-6 text-white" />
                  </div>
                  <Badge variant="outline" className="border-gray-700/50 bg-gray-800/30 text-gray-300 text-xs">
                    2,456 threats blocked
                  </Badge>
                </div>
                <CardTitle className="mt-4 text-lg text-white group-hover:text-red-400 transition-colors duration-300">
                  Phishing Emails
                </CardTitle>
                <CardDescription className="text-gray-300 leading-relaxed text-sm">
                  Identify suspicious emails and protect against phishing attempts with advanced detection.
                </CardDescription>
              </CardHeader>
              <CardFooter>
                <Button
                  disabled
                  className="w-full bg-gray-800/50 text-gray-500 border border-gray-700/50 cursor-not-allowed"
                >
                  <span>Coming Soon</span>
                </Button>
              </CardFooter>
            </Card>

            {/* Verify Documents - Coming Soon */}
            <Card
              key="verify-documents"
              className="group backdrop-blur-sm border text-white transition-all duration-300 hover:shadow-lg transform hover:scale-[1.02]"
              style={{
                backgroundColor: "#13151f/90",
                borderColor: "#22c55e/30",
              }}
            >
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-green-500 to-green-600 shadow-lg group-hover:scale-110 transition-transform duration-300">
                    <FileText className="h-6 w-6 text-white" />
                  </div>
                  <Badge variant="outline" className="border-gray-700/50 bg-gray-800/30 text-gray-300 text-xs">
                    10M+ documents indexed
                  </Badge>
                </div>
                <CardTitle className="mt-4 text-lg text-white group-hover:text-green-400 transition-colors duration-300">
                  Verify Documents
                </CardTitle>
                <CardDescription className="text-gray-300 leading-relaxed text-sm">
                  Check documents for plagiarism against a vast database of academic and published works.
                </CardDescription>
              </CardHeader>
              <CardFooter>
                <Button
                  disabled
                  className="w-full bg-gray-800/50 text-gray-500 border border-gray-700/50 cursor-not-allowed"
                >
                  <span>Coming Soon</span>
                </Button>
              </CardFooter>
            </Card>

            {/* AI Content Detection - Coming Soon */}
            <Card
              key="ai-detection"
              className="group backdrop-blur-sm border text-white transition-all duration-300 hover:shadow-lg transform hover:scale-[1.02]"
              style={{
                backgroundColor: "#13151f/90",
                borderColor: "#a855f7/30",
              }}
            >
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-purple-500 to-purple-600 shadow-lg group-hover:scale-110 transition-transform duration-300">
                    <Bot className="h-6 w-6 text-white" />
                  </div>
                  <Badge variant="outline" className="border-gray-700/50 bg-gray-800/30 text-gray-300 text-xs">
                    95% detection rate
                  </Badge>
                </div>
                <CardTitle className="mt-4 text-lg text-white group-hover:text-purple-400 transition-colors duration-300">
                  AI Content Detection
                </CardTitle>
                <CardDescription className="text-gray-300 leading-relaxed text-sm">
                  Identify content generated by AI tools like ChatGPT, Bard, and other language models.
                </CardDescription>
              </CardHeader>
              <CardFooter>
                <Button
                  disabled
                  className="w-full bg-gray-800/50 text-gray-500 border border-gray-700/50 cursor-not-allowed"
                >
                  <span>Coming Soon</span>
                </Button>
              </CardFooter>
            </Card>
          </div>
        </div>

        <Card className="backdrop-blur-sm border-gray-800/50 text-white" style={{ backgroundColor: "#13151f/80" }}>
          <CardHeader>
            <CardTitle className="flex items-center gap-3 text-xl">
              <div
                className="p-2 rounded-lg"
                style={{ background: "linear-gradient(135deg, #5068c9 0%, #4056b8 100%)" }}
              >
                <Zap className="h-5 w-5 text-white" />
              </div>
              Quick Actions
            </CardTitle>
            <CardDescription className="text-gray-400">Fast access to common verification tasks</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              <Button
                asChild
                variant="outline"
                className="group flex h-20 flex-col items-center justify-center gap-3 border-gray-700/50 bg-gray-800/30 p-4 text-gray-300 hover:bg-gray-700/50 hover:text-white transition-all duration-300"
                style={{ borderColor: "#5068c9/30" }}
              >
                <Link to="/verify-websites">
                  <FileCheck className="h-6 w-6 group-hover:text-[#5068c9] transition-colors duration-300" />
                  <span className="font-medium">Scan Project</span>
                </Link>
              </Button>
              <Button
                disabled
                variant="outline"
                className="flex h-20 flex-col items-center justify-center gap-3 border-gray-700/50 bg-gray-800/20 p-4 text-gray-500 cursor-not-allowed opacity-50"
              >
                <Globe className="h-6 w-6" />
                <span className="font-medium">Check URL</span>
              </Button>
              <Button
                disabled
                variant="outline"
                className="flex h-20 flex-col items-center justify-center gap-3 border-gray-700/50 bg-gray-800/20 p-4 text-gray-500 cursor-not-allowed opacity-50"
              >
                <Mail className="h-6 w-6" />
                <span className="font-medium">Verify Email</span>
              </Button>
              <Button
                disabled
                variant="outline"
                className="flex h-20 flex-col items-center justify-center gap-3 border-gray-700/50 bg-gray-800/20 p-4 text-gray-500 cursor-not-allowed opacity-50"
              >
                <Bot className="h-6 w-6" />
                <span className="font-medium">AI Check</span>
              </Button>
            </div>
          </CardContent>
        </Card>
      </main>

      <footer
        className="border-t border-gray-800/50 backdrop-blur-sm py-6 text-center text-sm text-gray-400"
        style={{ backgroundColor: "#0d0e16/50" }}
      >
        <p>© 2025 SecureSight by Arman Datt. All rights reserved.</p>
      </footer>
    </div>
  )
}

export default Dashboard
