import { Link } from "react-router-dom"
import Navbar from "../components/SSBlocks/NavBar"
import Footer from "../components/SSBlocks/Footer"
import { Button } from "../components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../components/ui/card"
import { Badge } from "../components/ui/badge"
import { Globe, Mail, FileText, Bot, ArrowRight } from "lucide-react"

// Feature data
const features = [
  {
    id: "project-authenticator",
    icon: <Globe className="h-10 w-10" style={{ color: "#5068c9" }} />,
    route: "project-authenticator",
    title: "Project Authenticator",
    description:
      "Detect plagiarized content across projects and identify potential copyright infringements. Our AI-powered tool helps ensure intellectual property protection and content originality with advanced similarity detection algorithms.",
    badge: "98% accuracy",
    color: "bg-[#5068c9]/10",
    iconColor: "text-[#5068c9]",
    available: true,
  },
  {
    id: "phishing-emails",
    icon: <Mail className="h-10 w-10 text-gray-400" />,
    route: "phishing-emails",
    title: "Phishing Emails",
    description:
      "Stay ahead of evolving phishing attacks with our advanced phishing email detection tool. Using AI and pattern recognition to identify suspicious emails and malicious links.",
    badge: "Coming Soon",
    color: "bg-gray-500/10",
    iconColor: "text-gray-400",
    available: false,
  },
  {
    id: "verify-documents",
    icon: <FileText className="h-10 w-10 text-gray-400" />,
    route: "verify-documents",
    title: "Verify Documents",
    description:
      "Instantly verify the authenticity and originality of documents using our document verification system with access to over 10 million indexed documents.",
    badge: "Coming Soon",
    color: "bg-gray-500/10",
    iconColor: "text-gray-400",
    available: false,
  },
  {
    id: "ai-content-detection",
    icon: <Bot className="h-10 w-10 text-gray-400" />,
    route: "ai-detection",
    title: "AI Content Detection",
    description:
      "Identify content generated by AI systems with industry-leading detection rates. Perfect for educators and researchers to differentiate human-written from machine-generated content.",
    badge: "Coming Soon",
    color: "bg-gray-500/10",
    iconColor: "text-gray-400",
    available: false,
  },
]

const isAuthenitcated = () => {
  const token = localStorage.getItem("token")
  if (token) {
    return true
  } else {
    return false
  }
}

export default function SolutionsPage() {
  return (
    <>
      <Navbar />
      <div className="min-h-screen" style={{ backgroundColor: "#0e1019" }}>
        <div className="container py-16 md:py-24">
          <div className="mx-auto max-w-[58rem] text-center mb-16">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl mb-4 text-white">Our Solutions</h1>
            <p className="text-xl text-gray-300">
              Comprehensive verification tools to protect your digital assets and ensure content authenticity.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {features.map((feature) => (
              <Card
                key={feature.id}
                className={`overflow-hidden border transition-all duration-300 ${
                  feature.available
                    ? "border-[#5068c9]/30 bg-slate-800/50 backdrop-blur hover:border-[#5068c9]/50 hover:shadow-lg hover:shadow-[#5068c9]/20"
                    : "border-gray-700/30 bg-slate-800/50 backdrop-blur hover:border-gray-600/50 hover:shadow-lg hover:shadow-gray-500/10"
                }`}
              >
                <CardHeader className={`${feature.color} p-6 relative`}>
                  {feature.available && (
                    <div className="absolute top-2 right-2 z-10">
                      <Badge className="bg-green-500 text-white text-xs px-2 py-1 animate-pulse">LIVE</Badge>
                    </div>
                  )}
                  <div className="flex items-center justify-between">
                    <div className={`rounded-full p-2 ${feature.color}`}>{feature.icon}</div>
                    <Badge
                      variant="secondary"
                      className={`text-xs ${
                        feature.available ? "bg-[#5068c9]/20 text-[#5068c9]" : "bg-gray-600/20 text-gray-400"
                      }`}
                    >
                      {feature.badge}
                    </Badge>
                  </div>
                  <CardTitle className="mt-4 text-2xl text-white">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent className="p-6">
                  <CardDescription className="text-base text-gray-300">{feature.description}</CardDescription>
                </CardContent>
                <CardFooter className="p-6 pt-0">
                  {feature.available ? (
                    isAuthenitcated() ? (
                      <Button asChild className="w-full bg-[#5068c9] hover:bg-[#5068c9]/80 text-white">
                        <Link to={`https://thesecuresight.com/${feature.route}`}>
                          Launch Tool
                          <ArrowRight className="ml-2 h-4 w-4" />
                        </Link>
                      </Button>
                    ) : (
                      <Button asChild className="w-full bg-[#5068c9] hover:bg-[#5068c9]/80 text-white">
                        <Link to={`/sign-in`}>
                          Launch Tool
                          <ArrowRight className="ml-2 h-4 w-4" />
                        </Link>
                      </Button>
                    )
                  ) : (
                    <Button disabled className="w-full bg-gray-600/20 text-gray-400 cursor-not-allowed">
                      Coming Soon
                    </Button>
                  )}
                </CardFooter>
              </Card>
            ))}
          </div>

          <div className="mt-16 text-center">
            <h2 className="text-2xl font-bold mb-4 text-white">Need a Custom Solution?</h2>
            <p className="text-gray-300 mb-6">
              We offer tailored verification solutions for enterprises with specific requirements.
            </p>
            <Button asChild size="lg" className="bg-[#5068c9] hover:bg-[#5068c9]/80 text-white">
              <Link to="/contact">Contact Our Team</Link>
            </Button>
          </div>
        </div>
      </div>
      <Footer />
    </>
  )
}
