import { Link } from "react-router-dom"
import Navbar from "../components/SSBlocks/NavBar"
import Footer from "../components/SSBlocks/Footer"
import { Button } from "../components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../components/ui/card"
import { Badge } from "../components/ui/badge"
import { Globe, Mail, FileText, Bot, ArrowRight } from "lucide-react"

// Feature data
const features = [
  {
    id: "verify-websites",
    icon: <Globe className="h-10 w-10 text-blue-500" />,
    route : "verify-websites",
    title: "Verify Websites",
    description: "Our AI-powered website verification tool helps detect plagiarized or copied content across the internet, ensuring intellectual property protection and content originality. Whether you're auditing academic articles, blogs, or product content, this tool identifies unauthorized reuse and potential copyright infringements, helping safeguard your digital assets.",
    badge: "98% accuracy",
    color: "bg-blue-500/10",
    iconColor: "text-blue-500",
  },
  {
    id: "phishing-emails",
    icon: <Mail className="h-10 w-10 text-red-500" />,
    route : "phishing-emails",
    title: "Phishing Emails",
    description: "Stay ahead of evolving phishing attacks with our advanced phishing email detection tool. Using AI and pattern recognition, it identifies suspicious emails, fake sender domains, and embedded malicious links to prevent potential breaches and protect sensitive information. Ideal for organizations and institutions looking to strengthen their cybersecurity posture.",
    badge: "2,456 threats blocked",
    color: "bg-red-500/10",
    iconColor: "text-red-500",
  },
  {
    id: "verify-documents",
    icon: <FileText className="h-10 w-10 text-green-500" />,
    route : "verify-documents",
    title: "Verify Documents",
    description: "Instantly verify the authenticity and originality of documents using our document verification system. It scans through a vast indexed repository of over 10 million documents, including academic submissions, resumes, certifications, and business documents, helping detect duplicates, AI-generated content, and forged materials with high accuracy.",
    badge: "10M+ documents indexed",
    color: "bg-green-500/10",
    iconColor: "text-green-500",
  },
  {
    id: "ai-content-detection",
    icon: <Bot className="h-10 w-10 text-purple-500" />,
    route : "ai-detection",
    title: "AI Content Detection",
    description: "This feature helps identify content generated by AI systems (like ChatGPT, Bard, etc.) with an industry-leading 95% detection rate. Perfect for educators, hiring platforms, and researchers, our system analyzes linguistic patterns, perplexity, and semantic structure to differentiate human-written content from machine-generated text.",
    badge: "95% detection rate",
    color: "bg-purple-500/10",
    iconColor: "text-purple-500",
  },
]

const isAuthenitcated = () => {
  const token = localStorage.getItem("token");
  if (token) {
    return true;
  } else {
    return false;
  }
}

export default function SolutionsPage() {
  return (
    <>
      <Navbar />
      <div className="container py-16 md:py-24">
        <div className="mx-auto max-w-[58rem] text-center mb-16">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl mb-4">Our Solutions</h1>
          <p className="text-xl text-muted-foreground">
            Comprehensive verification tools to protect your digital assets and ensure content authenticity.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {features.map((feature) => (
            <Card key={feature.id} className="overflow-hidden border border-border/40 bg-background/60 backdrop-blur">
              <CardHeader className={`${feature.color} p-6`}>
                <div className="flex items-center justify-between">
                  <div className={`rounded-full p-2 ${feature.color}`}>{feature.icon}</div>
                  <Badge variant="secondary" className="text-xs">
                    {feature.badge}
                  </Badge>
                </div>
                <CardTitle className="mt-4 text-2xl">{feature.title}</CardTitle>
              </CardHeader>
              <CardContent className="p-6">
                <CardDescription className="text-base text-muted-foreground">{feature.description}</CardDescription>
              </CardContent>
              <CardFooter className="p-6 pt-0">

              { isAuthenitcated() ? (
                <Button asChild className="w-full">
                  <Link to={`https://secure-sight-armandatts-projects.vercel.app/${feature.route}`}>
                    Launch Tool
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              ) : (
                <Button asChild className="w-full">
                  <Link to={`/sign-in`}>
                    Launch Tool
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              )}
              </CardFooter>
            </Card>
          ))}
        </div>

        <div className="mt-16 text-center">
          <h2 className="text-2xl font-bold mb-4">Need a Custom Solution?</h2>
          <p className="text-muted-foreground mb-6">
            We offer tailored verification solutions for enterprises with specific requirements.
          </p>
          <Button asChild size="lg">
            <Link to="/contact">Contact Our Team</Link>
          </Button>
        </div>
      </div>
      <Footer />
    </>
  )
}
